FROM golang:1.22.1-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

ENTRYPOINT ["./wait-for-it.sh", "postgres-test:5432", "--timeout=30", "--"]
CMD ["go", "test", "-v", "./..." ]